### ISSUE TITLE
Baseline: learning tool vs. support target

### ISSUE THREAD

**Issue by romainmenke** [web-platform-dx/feature-set#177]
I've already brought this up in the other issues but I think it should be discussed in detail.

- Is Baseline purely an indicator of when a feature is ready for learning?
- Is Baseline purely a support target?
- Is it both?

https://github.com/web-platform-dx/feature-set/issues/132#issuecomment-1544020886

-----

https://github.com/web-platform-dx/feature-set/issues/132#issue-1666599078

> Developers tell us that [keeping up with changes to the platform is a major issue for them](https://web.dev/deep-dive-into-developer-pain-points/). Due to the fragmented nature of the platform, the frequent browser releases and interoperability issues, developers have a hard time knowing when features are finally ready to use after hearing about them for a long time. This proposal attempts to address that fragmentation by providing developers with a profile of the web platform that we think will work for most developers most of the time.

As I understand this statement there are two issues embedded here :
- Users hear about features too early
- Users don't know when it is safe to use a feature

## Users hear about features too early

This is a logical consequence of browser vendor devrel teams who advocate features when they are added to the engine they represent.

The perfect time to share a new feature is when it is added to that browser.
But there is a good chance that one or both of the other engines don't have support yet.
So users are continually hearing about things that they perceive as unsafe to use.

I think there are some things that can help here :

1. A baseline that focusses on features that have shipped in all vendors, in any number of versions, for any amount of time. If all vendors shipped, it's ready to teach developers about this feature.

2. Keep teaching developers about progressive enhancement, graceful degradation, fallbacks, ... Even a feature that only exists in a single vendor can still be a valuable and safe addition to a project.

This possibly creates a culture where people are excited about new things and can apply these without harming end users.

Devrel teams can teach developers about new features at a knowable point in time instead of having to wait for months.

It also places all browsers on equal footing, regardless of their versioning/release patterns, taking away a source of toxicity within the dev community.

## Users don't know when it is safe to use a feature

"Safe to use a feature" could be defined as : 
- Bug reporting tools in use won't show error spikes
- Feedback channels won't receive complaints
- The usage/value of the product will not drop

I personally think this is simply unknowable without knowing something about what a developer is working on.

- Is the project for a single org who all have the same modern device?
- Is the project for students from families below the poverty line?
- Is the project for an institution where hardware, os versions are tied to other constraints?

The current industry standard for this problem is browserslist.

A developer configures their constraints as a query string and tools will help them deliver a working product.

Why can't we have the same in documentation?
Why can't I enter a browserslist query on MDN (localstorage?) so that this information can be used to place a label on documents I am reading?

Instead of just seeing `Baseline` or `Baseline 2023` it could say : `Fully adopted by your target group`.

If the full set of targeted browser versions isn't quite met, it can indicate this and link to learning materials on progressive enhancement, graceful degradation, fallbacks, ... 

This would actually give an answer to "is this safe for me to use?".

-----

As it currently stands I interpret Baseline as something that tries to do both with a single definition and is also not quite succeeding at this.

I think it would be helpful to split this up.

**Comment by romainmenke** [comment]
I've created a Chrome Extension to "inject" what I had in mind : https://chrome.google.com/webstore/detail/support-context/dcbelpbochjfadialnomdpnndkmmlpfo

It splits up the information into two distinct parts :
- percentage of targeted browsers that support the feature fully
- number of browsers engines that shipped an implementation

It has some bugs and shortcomings :
- It doesn't ignore preview/alpha/beta/nightly versions
- In large features like [`@media`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) where each engine is still to ship a sub-feature, it can only show `0% supported`
- Android/Chrome usage data needs to be completely ignored

The percentage of targeted browsers is calculated by taking the coverage of a user provided browserslist query and comparing that with the coverage of browsers with full support.

By comparing coverage it becomes less relevant whether or not the usage data is fully accurate. The general trend can still be informative and starts from the context of the developer.

------------

_It is still highly problematic that there isn't reliable usage data.
Having to work with the data from statcounter/caniuse is too limiting._

-------

I don't mean to say that this is thé way it should be done.
I only want to contribute an alternative method of informing developers on what is safe and what is ready for learning more about.

-------

Some examples :

`@media (hover)` :

<img width="844" alt="Screenshot 2023-05-15 at 19 14 07" src="https://github.com/web-platform-dx/feature-set/assets/11521496/6a4a5fbe-7496-4081-85bb-6fe62680d446">


`@layer` :

<img width="833" alt="Screenshot 2023-05-15 at 19 14 16" src="https://github.com/web-platform-dx/feature-set/assets/11521496/3a4c932f-12b2-46d7-9d55-8a2e1967392f">

`oklch` :

<img width="823" alt="Screenshot 2023-05-15 at 19 14 48" src="https://github.com/web-platform-dx/feature-set/assets/11521496/4bd460af-38cc-4f96-a5df-1e9f3b1bab08">

`:has()` :

<img width="815" alt="Screenshot 2023-05-15 at 19 16 25" src="https://github.com/web-platform-dx/feature-set/assets/11521496/6e7bdeac-224c-4f2a-a5d1-338697ece0bb">

**Comment by atopal** [comment]
> The current industry standard for this problem is browserslist.

Maybe it should be, but I have interviewed dozens of developers about how they handle feature availability across browsers and this is not the impression I have. I've heard anything from "Make it work in Chrome and fix it, if complaints come in after shipping" to "look at caniuse.com informally to see how green the feature looks" and many more, but browserlist only came up in libraries and open source projects I talked to. 

What you sketched out is already something that caniuse.com offers by connecting your Google Analytics account and getting accurate coverage per feature for your specific audience. I expect MDN to offer something similar in the future to customize the core browser set per user, it certainly was something we had already explored and wanted to offer when I was the product lead for MDN, but the data was not available yet. 

There is still value in providing an informed opinion on widely available features in the absence of more accurate individual data, specifically because many developers don't have the time or resources do dive into the specifics of a feature, and they still need to make a call and want guidance for that. I don't think there is a meaningful distinction between "ready to learn about" and "ready to be used", from my conversations with developers and devRel people. Developers mostly want to learn about things that they can use now, not at some unspecified time in the future, regardless of how stable the implementation is. 

Can you say more about why you think that developers value that distinction that would warrant having two different definitions of "widely available"?

**Comment by romainmenke** [comment]
> Can you say more about why you think that developers value that distinction that would warrant having two different definitions of "widely available"?

I was under the impression that there was a strong motivation to align Baseline to fairly recent releases. I got this impressions because of the current + 1 definition.

If the true goal is to express "safe to use" and that "safe to use" implies "ready to learn about" then that would be ideal and then there would be no need for two different definitions.

I do think this makes the feature less useful to vendors and devrel who want to teach developers about developers shortly after they become available.

I was trying to balance these two things :
- it might take 5 years for something to be really safe to use
- vendors want to features that have shipped to be well understood and that features are used

**Comment by atopal** [comment]
Ah, I don't think vendors will hold back talking about features they have just made available in their browser. That's often needed to get feedback around the implementation (see View Transitions), but also because some devs like being on the cutting edge and browsers will continue to experiment. But this gives us an option to talk about it twice: once when the feature is launched in one browser and then again when the feature can be used by the wider public. Yes, sometimes that can take 5 years or even longer (see Subgrid), but that doesn't devalue the concept. 

With Subgrid as the example: it was shipped 4 years ago in Firefox and will be shipped this year in Chrome. It made sense for Mozilla to gather feedback from devs back then, it will make sense to talk about it again once it's shipped across all browsers and widely available some time this year or next.

**Comment by romainmenke** [comment]
> it will make sense to talk about it again once it's shipped across all browsers and widely available some time this year or next.

Is it still acceptable when it takes 4 years, or 5 years after all vendors shipped? :)
I am trying to better understand if a definition that really fits "safe to use" would still be ok for everyone.

_More research will most likely indicate that it takes a very long time for anything to become truly widely available._

**Comment by atopal** [comment]
Our definition of widely available would need to meet developer expectations not just some abstract threshold, I'm pretty sure that's not 4-5 years after it's shipped across all browsers, my hunch is that it's closer to 1 or 2 years. Because of that, I don't see a conflict.

**Comment by romainmenke** [comment]
Cool! Thank you for clarifying all this :)

I think this issue can be closed?

**Comment by captainbrosset** [comment]
Related anecdote: https://github.com/web-platform-dx/feature-set/issues/245 

> From my personal point of view this would be great - especially for beginners - to know what to learn with higher priority.
